/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MiniProject;
import Classes.*;
import static MiniProject.Main_Home.Current_Department_Index;
import static MiniProject.Main_Home.Esi;
import java.util.ArrayList;

/**
 *
 * @author OKBA
 */
public class AddSalle_tp extends javax.swing.JFrame {

    
    public AddSalle_tp() {
        initComponents();
        setDefaultCloseOperation(AddSalle_tp.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clearTPSalleButton = new javax.swing.JButton();
        saveTPSalleButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nTable_input = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        N_building_input = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Building_name_input = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        building_area_input = new javax.swing.JTextField();
        capacity_input = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DepartmentTypeComboBox = new javax.swing.JComboBox<>();
        salleerrorlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clearTPSalleButton.setText("Clear");
        clearTPSalleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTPSalleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearTPSalleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 110, 50));

        saveTPSalleButton.setText("Save");
        saveTPSalleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTPSalleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveTPSalleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 110, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Number of Tables:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        nTable_input.setText("20 table");
        getContentPane().add(nTable_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 120, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Number of Building :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        N_building_input.setText("1");
        N_building_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N_building_inputActionPerformed(evt);
            }
        });
        getContentPane().add(N_building_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 120, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Building Name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        Building_name_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Building_name_inputActionPerformed(evt);
            }
        });
        getContentPane().add(Building_name_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 120, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Building area :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        building_area_input.setText("24");
        building_area_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                building_area_inputActionPerformed(evt);
            }
        });
        getContentPane().add(building_area_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 120, 40));

        capacity_input.setText("20");
        getContentPane().add(capacity_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 120, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Capacity :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Department:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        DepartmentTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prepa", "Sup" }));
        getContentPane().add(DepartmentTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 120, 40));

        salleerrorlabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        salleerrorlabel.setForeground(new java.awt.Color(255, 0, 51));
        salleerrorlabel.setText("Please Fill all the fields");
        getContentPane().add(salleerrorlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveTPSalleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTPSalleButtonActionPerformed
        // get the infos
        int index = DepartmentTypeComboBox.getSelectedIndex(); //department index 0 prepa 1 sup
        String tablesNumber = nTable_input.getText();
        int buildingsNumber = Integer.parseInt(N_building_input.getText());
        String buildingName = Building_name_input.getText();
        double buildingArea = Double.parseDouble(building_area_input.getText());
        int capacity = Integer.parseInt(capacity_input.getText());
        if (!N_building_input.getText().matches("[0-9]+") || !capacity_input.getText().matches("[0-9]+") || !building_area_input.getText().matches("([0-9]*[.])?[0-9]+")) {
            salleerrorlabel.setVisible(true);
            salleerrorlabel.setText("buildingsNumber, Area, capacity are type Number");
            return; 
        }
        if (tablesNumber.isEmpty() || N_building_input.getText().isEmpty() || buildingName.isEmpty() || building_area_input.getText().isEmpty() || capacity_input.getText().isEmpty()) {
            salleerrorlabel.setVisible(true);
            return;
        }
        for (TP_Salle st: Main_Home.salles) {
            if (st.buildingName.equals(buildingName)) {
                System.out.println(st.buildingName);
                salleerrorlabel.setVisible(true);
                salleerrorlabel.setText("Already Used Salle TP Name");
                return;
            }
        }
        //create the salle tp
        TP_Salle SalleTP = new TP_Salle(tablesNumber, buildingsNumber, buildingName, buildingArea, capacity);
        //add the salle tp to the salles arraylist
        Main_Home.salles.add(SalleTP);
        Esi.Departments[index].Blocks[0].add_TPSalle_to_Block(SalleTP);
        Main_Home.DepartementCompobox.setSelectedIndex(index+1);
        //refresh the salles array list show
        Main_Home.load_Salles(Esi.Departments[index].Blocks[0].Tp_Salles);
        Main_Home.print_salle_materials(new ArrayList<Materials>());
        Main_Home.TP_Salles_Jlist.setSelectedIndex(Main_Home.Esi.Departments[index].Blocks[0].getTPSalles().size()-1);
        this.setVisible(false);
    }//GEN-LAST:event_saveTPSalleButtonActionPerformed

    private void N_building_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N_building_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_N_building_inputActionPerformed

    private void building_area_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_building_area_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_building_area_inputActionPerformed

    private void clearTPSalleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTPSalleButtonActionPerformed
        //re initialize the old values
        nTable_input.setText("20 table");
        N_building_input.setText("1");
        Building_name_input.setText("");
        building_area_input.setText("24");
        capacity_input.setText("20");
    }//GEN-LAST:event_clearTPSalleButtonActionPerformed

    private void Building_name_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Building_name_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Building_name_inputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSalle_tp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSalle_tp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSalle_tp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSalle_tp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSalle_tp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Building_name_input;
    private static javax.swing.JComboBox<String> DepartmentTypeComboBox;
    private javax.swing.JTextField N_building_input;
    private javax.swing.JTextField building_area_input;
    private javax.swing.JTextField capacity_input;
    private javax.swing.JButton clearTPSalleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nTable_input;
    public static javax.swing.JLabel salleerrorlabel;
    private javax.swing.JButton saveTPSalleButton;
    // End of variables declaration//GEN-END:variables
}
